version: '3.8'

services:
  maven:
    build:
      context: .
    image: maven-build
    container_name: mvn_build
    working_dir: /app
    volumes:
      - .:/app                # Bind source code for build
      - ./target:/app/target # Store build artifacts
    command: mvn clean package -DskipTests

  tomcat:
    build:
      context: ./tomcat
    image: custom-tomcat
    container_name: tomcat
    ports:
      - "8080:8080"
    depends_on:
      - maven
    volumes:
      - ./target:/usr/local/tomcat/webapps
    restart: always
