version: '3.8'

services:
  maven:
    build:
      context: .
    image: maven-build
    container_name: mvn_build
    volumes:
      - ./target:/app/target   # so WAR can be reused by Tomcat
    command: mvn clean package -DskipTests

  tomcat:
    build:
      context: ./tomcat
    image: tomcat
    container_name: tomcat
    ports:
      - "8080:8080"
    depends_on:
      - maven
    volumes:
      - ./target:/usr/local/tomcat/webapps  # mount WAR into Tomcat
    restart: always
