apiVersion: v1
kind: Service
metadata:
  name: springapp-tomcat-service
spec:
  type: NodePort
  selector:
    app: springapp-tomcat
  ports:
    - name: http
      port: 80              # Exposes service on port 80 internally
      targetPort: 8080      # Forwards to pod’s containerPort
      nodePort: 30080       # Optional: static NodePort (range 30000–32767)
      protocol: TCP
