apiVersion: v1
kind: Service
metadata:
  name: springapp-tomcat-service
spec:
  type: NodePort
  selector:
    app: springapp-tomcat
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
